version: '3'
services:
  couch:
    image: couchdb:2.3.1
    restart: always
    volumes:
      - couchdb-data:/usr/local/var/lib/couchdb
    ports:
      - "5984:5984"
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run serve
    ports:
      - "9000:9000"
    volumes:
      - ./src:/opt/doubletrouble/src
      - ./data:/opt/doubletrouble/data
      - ./dist:/opt/doubletrouble/dist
    depends_on:
      - couch
    env_file: 
      - ./.env
  # nginx:
  #   build:
  #     dockerfile: Dockerfile.nginx
  #     context: .
  #   ports:
  #     - "9000:80"
  #   volumes:
  #     - ./dist:/opt/doubletrouble/dist
  #   depends_on:
  #     - web
volumes:
  couchdb-data:
  dist: