version: '3'
services:
  couch:
    image: couchdb:2.3.1
    restart: always
    volumes:
      - couchdb-data:/usr/local/var/lib/couchdb
    ports:
      - "5984:5984"
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - couch
    env_file: 
      - ./.env
volumes:
  couchdb-data:
